### ISSUE TITLE
After server restart, our Planka installation has disappeared

### ISSUE THREAD

**Issue by harryburr3** [plankanban/planka-installer#1]
Hi there.

We have been using Planka for a couple of weeks now after we installed using this one-click installer, and a colleague of mine reported it was inaccessible for him. Therefore, we rebooted the server, and it was working for me (still not for him) for another couple of hours, until it became inaccessible for me as well. I have attempted to re-run the docker compose script from the docs, and by the looks of the directories our installation has completely disappeared (pre docker compose script)

This might just be me not looking in the right directories and Planka is still there, is there some sort of service we need to restart perhaps? The installation URL is URL_REMOVED, and we're running through Linode.

This is a real shame since there was a lot of important information about our not-for-profit on the system, and we really need to recover that info (so can't just 're-install')

Any help would be greatly appreciated, and it would also be interesting to know whether this issue can be duplicated on another server.

Thanks.

**Comment by daniel-hiller** [comment]
Hi Harry,

just to be open to the community.
Harry also contacted us via email.
Due to the fact that it is a non-profit organization. We gave them free professional support via email.

The problem had nothing to do with the installer or Planka.
Planka was up and running, they had a simple DNS issue.

Greetings Daniel

**Comment by krussedull** [comment]
and what was the issue?
