### ISSUE TITLE
Installation issue with demo account

### ISSUE THREAD

**Issue by yukifury** [plankanban/planka-installer#2]
After auto-installation account demo@demo.demo in not existing. What I did wrong?

**Comment by meltyshev** [comment]
Hi! Thanks for reporting this.
We haven't yet updated the installer since the last change in Planka :(

As a workaround you can add these environment variables to the `/opt/planka/docker-compose.yml`:
```
...
environment:
	...
	DEFAULT_ADMIN_EMAIL=demo@demo.demo # Do not remove if you want to prevent this user from being edited/deleted
	DEFAULT_ADMIN_PASSWORD=demo
	DEFAULT_ADMIN_NAME=Demo Demo
	DEFAULT_ADMIN_USERNAME=demo
...
```
And then restart Planka.

**Comment by yukifury** [comment]
How to restart planka? Restart function from installer doesn't working

**Comment by meltyshev** [comment]
Please try to restart it by:
```
docker compose down
docker compose up -d
```
Note: should be executed in the `/opt/planka/` folder.

**Comment by yukifury** [comment]
Finally! It's working, thanks.

However, 

```
 ...
 environment:
 	...
	- DEFAULT_ADMIN_EMAIL=demo@demo.demo # Do not remove if you want to prevent this user from being edited/deleted
 	- DEFAULT_ADMIN_PASSWORD=demo
 	- DEFAULT_ADMIN_NAME=Demo Demo
 	- DEFAULT_ADMIN_USERNAME=demo
 ...
```

that's corrected version.

Thank you for fast answer!

**Comment by meltyshev** [comment]
Great! A little clarification about these environment variables:
You can remove them after installation to be able to change the password directly in Planka. If the `DEFAULT_ADMIN_EMAIL` variable is present, then this user will be locked and can't be changed. But in any case it's better not to store a password in the `/opt/planka/docker-compose.yml` file, just use these variables in case you need to reset an admin password.
